name: Android CI

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Gradle
      run: |
          echo "Going to working dir MinimumApps"
          cd MiniumApps
          echo "Add execution right to gradlew script"
          chmod +x gradlew
          echo "Start alpha debug build"
          ./gradlew :launcher3:assembleDebug

    - name: Save built apk
      uses: actions/upload-artifact@v2
      with:
        path: MiniumApps/launcher3/build/outputs/apk/debug/launcher3*.apk
