name: Android CI

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Go to working dir
      run: |
          echo "Working dir is `pwd`"
          echo "Working dir content:"
          ls -la
          cd MiniumApps
          echo "New working dir is `pwd`"
          echo "New working dir content"
          ls -la

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :assembleAlphaDebug
    - name: Save built apk
      uses: actions/upload-artifact@v2
      with:
        path: launcher3/build/outputs/apk/beta/debug/*.apk
